Repository OneMeditTeam/1Medit_Back_Office_Frontend, pull requests merged in 2025-02, with the labels that each got.

#12 feat: :sparkles: (#11): 테스트
  README.md
Labels: ✨ Feature

#14 feat: :sparkles: (#13) : Button 컴포넌트 생성 및 커스터마이징
  src/app/dashboard/page.tsx
  src/components/common/Button.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/pagination.tsx
Labels: 🎨 Html&css, ✨ Feature

#21 Chore/#20 eslint, prettier 설정
  .eslintrc.js
  .github/ISSUE_TEMPLATE/⚙chore-template.md
  .github/ISSUE_TEMPLATE/🎨other-template.md
  .github/ISSUE_TEMPLATE/🔧fix-template.md
  .github/ISSUE_TEMPLATE/🛠feature-template.md
  .github/workflows/netlify-deploy.yml
  .prettierrc
  components.json
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.js
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Button.tsx
  src/components/common/LeftNavigationBar.tsx
  src/components/common/Loading.tsx
  src/components/ui/accordion.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/pagination.tsx
  src/components/ui/sheet.tsx
  src/components/ui/table.tsx
  src/constants/menuItem.ts
  src/lib/utils.ts
  src/types/menu.ts
  src/utils/formatPhoneNumber.ts
  tailwind.config.js
Labels: ⚙ Setting, 🔨 Refactor
